// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '2.4.20'
    ext.agp_version = '9.4.1'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        // Provides com.android.legacy-kapt, the kapt plugin for AGP's built-in Kotlin support.
        classpath "com.android.tools.build:gradle-kotlin:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.37.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
